### ISSUE TITLE
Wrong MainForm button layout

### ISSUE THREAD

**Issue by 0xCA** [GuidoNeele/VersioningControlledBuild#1]
## Issue
In main window, right buttons are misaligned and messed:

![rightbuttons](https://cloud.githubusercontent.com/assets/11984323/23812939/5da53b3e-05fe-11e7-884d-9d6b8b40f2a6.png)
### System:
- Windows 10
  - 100% DPI Scaling
  - Tested at:
    - VS15
    - VS17

## Attempts to fix
I thought that it's a good idea to fix this, so I cloned the repository, restored all NuGet references, but keep getting errors.
![mainformerrors](https://cloud.githubusercontent.com/assets/11984323/23812988/92765c58-05fe-11e7-89db-75edee2cc443.png)
I have absolutely no idea why designer can't view a public class in same namespace.
If I ignore errors, form is loading, but w/o elements from errors.
I tried to build the solution and got no errors, as expected from what I saw in code.

Please, tell how to correctly load the project/designer and I'll make it beautifully aligned and pull here.
Or maybe just fix it by yourself..

**Comment by GuidoNeele** [comment]
I don't think the buttons are misaligned but the minimal height of the dialog should be a bit bigger.  The buttons overlap each other when the height of the dialog is set to it's minimal. When you increase the dialog height everything is looking fine.

**Comment by 0xCA** [comment]
Didn't notice that the window is not fixed-size.
Buttons are really ok and min height needs to be increased.
Also I'd suggest to increase minimum width too to avoid scrollbar at default size.
