### ISSUE TITLE
Major UI glitches in Visual Studio 2017

### ISSUE THREAD

**Issue by gbakeman** [GuidoNeele/VersioningControlledBuild#3]
I've been looking for a good version incrementer plugin, but so far the ones I've found all have the same problem - they cause huge UI glitches in Visual Studio 2017. I have **version 15.4.4**, and when the extension is active, nearly all of my UI becomes blank. If I move my mouse over, some elements start to appear, but all icons are missing.

![screenshot 1](https://user-images.githubusercontent.com/842942/32976449-ab8307d6-cbca-11e7-84af-730604fa2f12.png)

Edit: After a little more testing, this bug isn't as reproducible as I thought it was. It seems like installing/uninstalling extensions seems to trigger this bug at random. Eventually icons will start working, even if this extension remains enabled.

**Comment by GuidoNeele** [comment]
Hi Glen,

If all the extensions cause the same problems then the fault is probably with Visual Studio itself in stead of with all the extensions. Your problem might be related to https://developercommunity.visualstudio.com/content/problem/97438/missing-icons-after-update.html

**Comment by gbakeman** [comment]
Thank you for pointing that out, I apologize for jumping to conclusions.
