### ISSUE TITLE
Support for NetStandard and Core

### ISSUE THREAD

**Issue by LaraSQP** [GuidoNeele/VersioningControlledBuild#6]
First of all, thank you very, very much for maintaining this extension and bringing it up to VS 2019.

I understand that the extension is based on Sribar's code but he is not updating his and you are.

Any plans for NetStandard and Core support?

Thanks again.

**Comment by GuidoNeele** [comment]
At the moment I have no plans to update this project for .NET Standard and .NET Core. The only thing I did was bring the extension to VS 2015, 2017 and 2019, which was relatively easy. I haven't really looked at the mechanics behind updating the version numbers on projects. Doing this for .NET Standard and .NET Core would mean research and development and I'm afraid I can't find the time at the moment.

**Comment by LaraSQP** [comment]
I understand. Thanks for getting back.
