### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by MatthewJRyan** [GuidoNeele/VersioningControlledBuild#8]
Could you update this to support VS2022m cant currently install as not listed in Extensions?

Please & Thanks

**Comment by dlevinson5** [comment]
I created a PR with the necessary changes to use this with Visual Studio 2022. There are a number of other extensions that do this but yours handles C/C++ and Microsoft Setup Projects perfectly.

**Comment by GuidoNeele** [comment]
Thanks @dlevinson5 I've merged your PR and submitted the extension to the VS marketplace. Can be downloaded via https://marketplace.visualstudio.com/items?itemName=NeeleGuido.VersioningControlledBuild2022
